export const DEFAULT_MAX_QUERY_ROWS = 1000;
export const DEFAULT_QUERY_TIMEOUT_MS = 30_000;
export const DEFAULT_CONNECTION_TIMEOUT_MS = 10_000;
export const DEFAULT_POSTGRES_PORT = 5432;
export const DEFAULT_MYSQL_PORT = 3306;
